services:
  api:
    build:
      dockerfile: Dockerfile       
    container_name: socialrecipes-api-container
    ports:
      - "8080:8080"
    networks:
      - socialrecipes-network
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=mysql-db;Database=socialrecipesdb;User Id=root;Password=rootpassword;
    depends_on:
      - mysql-db

  frontend:
    build:
      context: ./Frontend  
    container_name: socialrecipesfrontend-container
    ports:
      - "3000:3000"
    networks:
      - socialrecipes-network
    volumes:
      - ./sessions:/app/sessions
    depends_on:
      - api
      
  mysql-db:
    image: mysql:8.0
    container_name: socialrecipes-mysql-db
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: socialrecipesdb
    networks:
      - socialrecipes-network
    volumes:
      - mysql_data:/var/lib/mysql
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql

  sonarqube:
    image: sonarqube:community
    container_name: sonarqube
    environment:
      - SONARQUBE_JDBC_URL=jdbc:postgresql://sonarqube-db:5432/sonar
      - SONARQUBE_JDBC_USERNAME=sonar
      - SONARQUBE_JDBC_PASSWORD=sonar
    ports:
      - "9000:9000"
    depends_on:
      - sonarqube-db
    networks:
      - socialrecipes-network

  sonarqube-db:
    image: postgres:13
    container_name: sonarqube-db
    environment:
      - POSTGRES_USER=sonar
      - POSTGRES_PASSWORD=sonar
      - POSTGRES_DB=sonar
    volumes:
      - sonarqube_db_data:/var/lib/postgresql/data
    networks:
      - socialrecipes-network

networks:
  socialrecipes-network:
    driver: bridge

volumes:
  mysql_data:
  sessions:
  sonarqube_db_data:
