name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    name: Build and Test 
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Debug File Paths
      run: ls -l  # List files to verify paths

    - name: pwd check
      run: pwd

    - name: Set up Docker Compose
      run: |
        docker-compose down || true
        docker-compose up -d --build
        

    - name: Wait for Services to be Ready
      run: |
        sleep 15
        docker ps

    - name: Run API Tests
      run: |
        docker exec socialrecipes-api-container dotnet test --no-build --logger "trx;LogFileName=test_results.trx"

    - name: Upload Test Results
      uses: actions/upload-artifact@v3
      with:
        name: test-results
        path: ./SocialRecipes.API/TestResults/*.trx

    - name: Tear Down Docker Compose
      if: always()
      run: docker-compose down

  deploy:
    name: Deploy Locally
    runs-on: ubuntu-latest
    needs: build-and-test
    if: success()

    steps:
    - name: Tag Production Images
      run: |
        docker tag socialrecipes-api-container myapp/api:prod
        docker tag socialrecipesfrontend-container myapp/frontend:prod

    - name: Notify Deployment Success
      run: echo "Local production images have been tagged successfully!"
