name: Run Cypress Tests

on: 
  push:
    branches:
      - master  
  pull_request:
    branches:
      - master 

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3 

    - name: Set up Node.js
      uses: actions/setup-node@v3  
      with:
        node-version: 16  

    - name: Install dependencies
      run: npm install
      working-directory: Frontend  # Correct path to frontend

    - name: Start server
      run: npm start &
      env:
        NODE_ENV: test  
      working-directory: Frontend  # Correct path to frontend

    - name: Wait for server to be ready
      run: npx wait-on http://localhost:3000 
      working-directory: Frontend  # Correct path to frontend

    - name: Run Cypress tests
      uses: cypress-io/github-action@v2
      with:
        browser: chrome
        config-file: Frontend/cypress.config.js  # Correct path to Cypress config in frontend
        working-directory: Frontend  # Set working directory to Frontend for Cypress
      env:
        CYPRESS_baseUrl: http://localhost:3000  

    - name: Upload Cypress test artifacts
      if: failure()
      uses: actions/upload-artifact@v3  
      with:
        name: cypress-screenshots
        path: Frontend/cypress/screenshots  # Path to screenshots in Frontend directory

    - name: Upload Cypress videos
      if: failure()
      uses: actions/upload-artifact@v3 
      with:
        name: cypress-videos
        path: Frontend/cypress/videos  # Path to videos in Frontend directory
