name: Run Cypress Tests

on: 
  push:
    branches:
      - master  
  pull_request:
    branches:
      - master 

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3 

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Set up Docker Compose
      run: sudo apt-get install docker-compose

    - name: Build and Start Containers
      run: docker-compose up -d --build  

    - name: Wait for frontend to be ready
      run: npx wait-on http://localhost:3000 

    - name: Run Cypress tests
      uses: cypress-io/github-action@v2
      with:
        browser: chrome
        config-file: Frontend/cypress.config.js
      env:
        CYPRESS_baseUrl: http://localhost:3000  

    - name: Upload Cypress test artifacts
      if: failure()
      uses: actions/upload-artifact@v3  
      with:
        name: cypress-screenshots
        path: Frontend/cypress/screenshots  

    - name: Upload Cypress videos
      if: failure()
      uses: actions/upload-artifact@v3 
      with:
        name: cypress-videos
        path: Frontend/cypress/videos 

    - name: Stop and Remove Containers
      run: docker-compose down  
