name: Run Cypress Tests

on: 
  push:
    branches:
      - master 
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3 

    - name: Set up Node.js
      uses: actions/setup-node@v3  
      with:
        node-version: 16  

    - name: Install dependencies
      run: npm install
      working-directory: SocialRecipes.API/frontend  # Absolute path from repository root

    - name: Start server
      run: npm start &
      env:
        NODE_ENV: test  
      working-directory: SocialRecipes.API/frontend  # Absolute path from repository root

    - name: Wait for server to be ready
      run: npx wait-on http://localhost:3000 
      working-directory: SocialRecipes.API/frontend  # Absolute path from repository root

    - name: Run Cypress tests
      uses: cypress-io/github-action@v2
      with:
        browser: chrome
        config-file: SocialRecipes.API/frontend/cypress.config.js  # Path to Cypress config in frontend
      env:
        CYPRESS_baseUrl: http://localhost:3000  

    - name: Upload Cypress test artifacts
      if: failure()
      uses: actions/upload-artifact@v3  
      with:
        name: cypress-screenshots
        path: SocialRecipes.API/frontend/cypress/screenshots  # Path to screenshots in frontend directory

    - name: Upload Cypress videos
      if: failure()
      uses: actions/upload-artifact@v3 
      with:
        name: cypress-videos
        path: SocialRecipes.API/frontend/cypress/videos  # Path to videos in frontend directory
