name: Build and Deploy to ACI

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build-and-deploy:
    name: Build and Deploy to ACI
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Log in to ACR
        run: |
          az acr login --name SocialRecipes

      - name: Docker Login to ACR
        run: |
          echo ${{ secrets.AZURE_ACR_PASSWORD }} | docker login SocialRecipes.azurecr.io --username ${{ secrets.AZURE_ACR_USERNAME }} --password-stdin

      - name: Build and Push API Image
        run: |
          docker build -f Dockerfile -t SocialRecipes.azurecr.io/socialrecipes-api:${{ github.sha }} .
          docker push SocialRecipes.azurecr.io/socialrecipes-api:${{ github.sha }}

      - name: Build and Push Frontend Image
        run: |
          docker build -f ./Frontend/Dockerfile -t SocialRecipes.azurecr.io/socialrecipes-frontend:${{ github.sha }} ./Frontend
          docker push SocialRecipes.azurecr.io/socialrecipes-frontend:${{ github.sha }}

      - name: Deploy API to ACI
        run: |
            az container create \
            --resource-group SocialRecipes \
            --name socialrecipes-api \
            --image socialrecipes.azurecr.io/socialrecipes-api:${{ github.sha }} \
            --cpu 1 --memory 1.5Gb \
            --registry-login-server socialrecipes.azurecr.io \
            --registry-username ${{ secrets.AZURE_ACR_USERNAME }} \
            --registry-password ${{ secrets.AZURE_ACR_PASSWORD }} \
            --dns-name-label socialrecipes-api-${{ github.sha }} \
            --ports 80 \
            --debug
  
      - name: Deploy Frontend to ACI
        run: |
            az container create \
              --resource-group SocialRecipes \  
              --name socialrecipes-frontend \
              --image socialrecipes.azurecr.io/socialrecipes-frontend:${{ github.sha }} \
              --cpu 1 --memory 1.5Gb \
              --registry-login-server socialrecipes.azurecr.io \
              --registry-username ${{ secrets.AZURE_ACR_USERNAME }} \
              --registry-password ${{ secrets.AZURE_ACR_PASSWORD }} \
              --dns-name-label socialrecipes-frontend-${{ github.sha }} \
              --ports 80