name: CI/CD Pipeline
# test can i please push this file
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build-and-test:
    name: Build and Test
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Display Current Working Directory (Initial)
      run: pwd

    - name: Check Docker Compose Installation
      run: docker-compose version

    - name: Set up Docker Compose
      run: |
        docker-compose down || true
        docker-compose up -d --build