name: Run Unit Tests on Windows

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest 

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '4.7.2'  # Set the correct .NET Framework version

    - name: Restore dependencies
      run: dotnet restore

    - name: Build the project
      run: dotnet build --configuration Release

    - name: Run unit tests
      run: dotnet test --no-build --verbosity normal
