name: SonarQube Analysis
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch:

jobs:
  build-and-analyze:
    name: build and analyze with sonarqube
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'

    - name: Install Dependencies
      working-directory: ./Frontend
      run: npm install

    - name: Run Tests
      working-directory: ./Frontend
      run: npx nyc npx qunit

    - name: SonarQube Analysis
      working-directory: ./Frontend
      env:
        SONAR_HOST_URL: http://localhost:9000
        SONAR_TOKEN: ${{ secrets.SONARQUBE_TOKEN }}
      run: |
        npx sonarqube-scanner \
          -Dsonar.projectKey=your-project-key \
          -Dsonar.sources=./src \
          -Dsonar.tests=./test \
          -Dsonar.javascript.lcov.reportPaths=coverage/lcov.info \
          -Dsonar.host.url=$SONAR_HOST_URL \
          -Dsonar.login=$SONAR_TOKEN